// <auto-generated />
using System;
using CoreCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("CoreCrud.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<int>("CountryId");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<int>("Score");

                    b.Property<string>("State");

                    b.Property<string>("Zip")
                        .IsRequired();

                    b.Property<string>("athlete_name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("game_end_time");

                    b.Property<DateTime>("game_start_time");

                    b.Property<bool>("win");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("CoreCrud.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country_name");

                    b.Property<string>("Nationality");

                    b.Property<int>("Population");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("CoreCrud.Models.Athlete", b =>
                {
                    b.HasOne("CoreCrud.Models.Country", "Country")
                        .WithMany("Athletes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
